// worker.ts — Cloudflare Worker entry (wrangler.jsonc "main").
// Wraps the OpenNext worker that `opennextjs-cloudflare build` writes to
// .open-next/worker.js with two things Vercel used to do at its edge:
//
// 1. Host redirects (formerly vercel.json): the old ccc.lukeghanna.com name
//    301s to the canonical clippers.lukeghanna.com, path and query kept.
// 2. A short shared cache for GET /api/live: the route sets
//    CDN-Cache-Control (max-age=2 during games, 30 when idle) and every poller
//    in a Cloudflare location shares one render per window. The Cache API only
//    works on a custom domain; on workers.dev it is a no-op and every request
//    renders.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by `opennextjs-cloudflare build`; absent before the first build
import { default as openNext } from './.open-next/worker.js'

interface WaitUntil {
  waitUntil(promise: Promise<unknown>): void
}

interface OpenNextWorker {
  fetch(request: Request, env: unknown, ctx: WaitUntil): Promise<Response>
}

const app = openNext as OpenNextWorker

const CANONICAL_ORIGIN = 'https://clippers.lukeghanna.com'
const REDIRECT_HOSTS = new Set(['ccc.lukeghanna.com'])

/** max-age from a CDN-Cache-Control header, in seconds (0 when absent). */
function cdnMaxAge(header: string | null): number {
  const match = header?.match(/(?:^|,)\s*max-age=(\d+)/)
  return match ? Number(match[1]) : 0
}

async function cachedLive(request: Request, env: unknown, ctx: WaitUntil): Promise<Response> {
  const cache = (caches as unknown as { default: Cache }).default
  const key = new Request(request.url, { method: 'GET' })
  const hit = await cache.match(key)
  if (hit) {
    // Stored with an edge TTL; hand browsers the route's own Cache-Control.
    const res = new Response(hit.body, hit)
    res.headers.set('Cache-Control', hit.headers.get('X-Browser-Cache-Control') ?? 'no-store')
    res.headers.delete('X-Browser-Cache-Control')
    return res
  }
  const res = await app.fetch(request, env, ctx)
  const ttl = cdnMaxAge(res.headers.get('CDN-Cache-Control'))
  if (res.status === 200 && ttl > 0) {
    const stored = new Response(res.clone().body, res)
    stored.headers.set('X-Browser-Cache-Control', res.headers.get('Cache-Control') ?? 'no-store')
    stored.headers.set('Cache-Control', `public, max-age=${ttl}`)
    ctx.waitUntil(cache.put(key, stored))
  }
  return res
}

const worker = {
  async fetch(request: Request, env: unknown, ctx: WaitUntil): Promise<Response> {
    const url = new URL(request.url)
    if (REDIRECT_HOSTS.has(url.hostname)) {
      return Response.redirect(`${CANONICAL_ORIGIN}${url.pathname}${url.search}`, 301)
    }
    if (request.method === 'GET' && url.pathname === '/api/live' && !request.headers.has('authorization')) {
      return cachedLive(request, env, ctx)
    }
    return app.fetch(request, env, ctx)
  },
}

export default worker
