// worker.ts — Cloudflare Worker entry (wrangler.jsonc "main").
// Wraps the OpenNext worker that `opennextjs-cloudflare build` writes to
// .open-next/worker.js with two things Vercel used to do at its edge:
//
// 1. Host redirects (formerly vercel.json): the old ccc.lukeghanna.com name
//    301s to the canonical clippers.lukeghanna.com, path and query kept.
// 2. A shared edge cache (src/lib/edge-cache.ts): pages and read-only APIs
//    declare a TTL with CDN-Cache-Control (next.config.ts; /api/live sets its
//    own 2 s / 30 s), and hits are served from the Cache API without running
//    Next.js. The Cache API only works on a custom domain; on workers.dev
//    every lookup misses and every request renders.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by `opennextjs-cloudflare build`; absent before the first build
import { default as openNext } from './.open-next/worker.js'
import { serveWithEdgeCache, type EdgeCacheStore, type WaitUntil } from './src/lib/edge-cache'

interface OpenNextWorker {
  fetch(request: Request, env: unknown, ctx: WaitUntil): Promise<Response>
}

const app = openNext as OpenNextWorker

const CANONICAL_ORIGIN = 'https://clippers.lukeghanna.com'
const REDIRECT_HOSTS = new Set(['ccc.lukeghanna.com'])

const worker = {
  async fetch(request: Request, env: unknown, ctx: WaitUntil): Promise<Response> {
    const url = new URL(request.url)
    if (REDIRECT_HOSTS.has(url.hostname)) {
      return Response.redirect(`${CANONICAL_ORIGIN}${url.pathname}${url.search}`, 301)
    }
    const store = (caches as unknown as { default: EdgeCacheStore }).default
    return serveWithEdgeCache(request, () => app.fetch(request, env, ctx), { store, ctx })
  },
}

export default worker
